/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FavoriteMeal {
  'id' : bigint,
  'name' : string,
  'slot' : string,
  'emoji' : string,
  'cuisine' : string,
}
export interface MealSuggestion {
  'id' : bigint,
  'name' : string,
  'slot' : string,
  'description' : string,
  'emoji' : string,
  'cuisine' : string,
}
export interface Place {
  'id' : bigint,
  'placeType' : string,
  'name' : string,
  'distance' : string,
  'cuisine' : string,
  'rating' : number,
}
export interface UserProfile {
  'displayName' : string,
  'dietaryPreferences' : Array<string>,
  'favoriteMeals' : Array<FavoriteMeal>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFavoriteMeal' : ActorMethod<[FavoriteMeal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavoriteMeals' : ActorMethod<[], Array<FavoriteMeal>>,
  'getMealSuggestions' : ActorMethod<[string, bigint], Array<MealSuggestion>>,
  'getNearbyPlaces' : ActorMethod<[string], Array<Place>>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getSupportedRegions' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFavoriteMeal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProfile' : ActorMethod<[string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];