/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FavoriteMeal = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'slot' : IDL.Text,
  'emoji' : IDL.Text,
  'cuisine' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'dietaryPreferences' : IDL.Vec(IDL.Text),
  'favoriteMeals' : IDL.Vec(FavoriteMeal),
});
export const MealSuggestion = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'slot' : IDL.Text,
  'description' : IDL.Text,
  'emoji' : IDL.Text,
  'cuisine' : IDL.Text,
});
export const Place = IDL.Record({
  'id' : IDL.Nat,
  'placeType' : IDL.Text,
  'name' : IDL.Text,
  'distance' : IDL.Text,
  'cuisine' : IDL.Text,
  'rating' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavoriteMeal' : IDL.Func([FavoriteMeal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavoriteMeals' : IDL.Func([], [IDL.Vec(FavoriteMeal)], ['query']),
  'getMealSuggestions' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(MealSuggestion)],
      ['query'],
    ),
  'getNearbyPlaces' : IDL.Func([IDL.Text], [IDL.Vec(Place)], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getSupportedRegions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFavoriteMeal' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProfile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FavoriteMeal = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'slot' : IDL.Text,
    'emoji' : IDL.Text,
    'cuisine' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'dietaryPreferences' : IDL.Vec(IDL.Text),
    'favoriteMeals' : IDL.Vec(FavoriteMeal),
  });
  const MealSuggestion = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'slot' : IDL.Text,
    'description' : IDL.Text,
    'emoji' : IDL.Text,
    'cuisine' : IDL.Text,
  });
  const Place = IDL.Record({
    'id' : IDL.Nat,
    'placeType' : IDL.Text,
    'name' : IDL.Text,
    'distance' : IDL.Text,
    'cuisine' : IDL.Text,
    'rating' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavoriteMeal' : IDL.Func([FavoriteMeal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavoriteMeals' : IDL.Func([], [IDL.Vec(FavoriteMeal)], ['query']),
    'getMealSuggestions' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(MealSuggestion)],
        ['query'],
      ),
    'getNearbyPlaces' : IDL.Func([IDL.Text], [IDL.Vec(Place)], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getSupportedRegions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFavoriteMeal' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProfile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };